### ISSUE TITLE
Deprecation warnings given for mongodb-backend.js

### ISSUE THREAD

**Issue by bazconz** [OptimalBits/node_acl#270]
mongodb@2.2.36 deprecation warnings as follows:
```
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
    at ~node_modules\acl\lib\mongodb-backend.js:128:20

DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
    at ~node_modules\acl\lib\mongodb-backend.js:138:20
```

**Comment by ThienTranDuy** [comment]
In my library, no change the commit of bazconz? @bazconz
